# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/

language: node_js
env: TRAVIS_CI=true

node_js:
  - "9"
  - "8"

cache:
  directories:
    - "node_modules"
  yarn: true

script:
  - npm run report
